nodes:
  - id: 0
    host: 128.105.146.7
    http_port: 6333
    grpc_port: 6334
    p2p_port: 6335
    ssh_user: dk
  - id: 1
    host: 128.105.145.249
    http_port: 6333
    grpc_port: 6334
    p2p_port: 6335
    ssh_user: dk
  - id: 2
    host: 128.105.145.234
    http_port: 6333
    grpc_port: 6334
    p2p_port: 6335
    ssh_user: dk

collection:
  name: sift128
  vector_size: 128
  distance: Euclid
  hnsw_config:
    m: 16
    ef_construct: 100
    full_scan_threshold: 10000
